/*

 BUBBLE.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define bubblesBank 0
extern unsigned char bubblesTLE0[];
extern unsigned char bubblesTLE1[];
extern unsigned char bubblesTLE2[];
extern unsigned char bubblesTLE3[];
extern unsigned char bubblesTLE4[];
extern unsigned char bubblesTLE5[];
extern unsigned char bubblesTLE6[];
extern unsigned char bubblesTLE7[];
extern unsigned char bubblesTLE8[];
extern unsigned char bubblesTLE9[];
extern unsigned char bubblesTLE10[];
extern unsigned char bubblesTLE11[];
extern unsigned char bubblesTLE12[];
extern unsigned char bubblesTLE13[];
extern unsigned char bubblesTLE14[];
extern unsigned char bubblesTLE15[];

/* End of BUBBLE.H */
