/*

 HALLWAYMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : D:\Documents\Senior Project\game3bkg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hallwayWidth 40
#define hallwayHeight 18
#define hallwayBank 0

extern unsigned char hallway[];

/* End of HALLWAYMAP.H */
