/*

 COIN.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char coin[] =
{
  0x3C,0x3C,0x62,0x42,0xE5,0x99,0xDB,0xA1,
  0xDB,0xA1,0xA7,0xC1,0x46,0x7A,0x3C,0x3C
};

/* End of COIN.C */
